### ISSUE TITLE
Brittany strips shebangs

### ISSUE THREAD

**Issue by pbrisbin** [lspitzner/brittany#192]
```
% brittany --version
brittany version 0.11.0.0
Copyright (C) 2016-2018 Lennart Spitzner
There is NO WARRANTY, to the extent permitted by law.
```

### Example

**/tmp/script**

```hs
#!/usr/bin/env stack
{- stack script --resolver lts -}
module Main where

import AnotherModule
import Data.Text

main :: IO ()
main = undefined
```

### Expected

```
% brittany /tmp/script
#!/usr/bin/env stack
{- stack script --resolver lts -}
module Main where

import AnotherModule
import Data.Text

main :: IO ()
main = undefined
```

(Shebang preserved.)

### Actual

```
% brittany /tmp/script

{- stack script --resolver lts -}
module Main where

import AnotherModule
import Data.Text

main :: IO ()
main = undefined
```

(The shebang was stripped.)

---

This makes brittany unusable for so-called "Stack Scripts", which are becoming quite popular.

**Comment by tfausak** [comment]
I think this is related to #92. I tried using both STDIN and a file; both worked. Can you try again and reopen this if it's still a problem? Thanks!

**Comment by pbrisbin** [comment]
I think this has regressed, specifically on usage with a file:

```console
% stack exec brittany -- --version
brittany version 0.12.0.0
Copyright (C) 2016-2018 Lennart Spitzner
There is NO WARRANTY, to the extent permitted by law.
% stack exec brittany < ./scripts/hello
#!/usr/bin/env stack
-- stack script --resolver lts-15.4
-- vim: ft=haskell
module Main
  ( main
  )
where

main :: IO ()
main = putStrLn "Hello"
% stack exec brittany ./hello

-- stack script --resolver lts-15.4
-- vim: ft=haskell
module Main
  ( main
  )
where

main :: IO ()
main = putStrLn "Hello"
```

Can we re-open?

**Comment by tfausak** [comment]
Seems like this has been fixed again:

``` sh
# cat issue-192.hs 
#! /usr/bin/env stack
-- stack --resolver lts-16.0 script
main = pure ()

# brittany issue-192.hs 
#! /usr/bin/env stack
-- stack --resolver lts-16.0 script
main = pure ()

# brittany --version
brittany version 0.12.1.1
Copyright (C) 2016-2019 Lennart Spitzner
Copyright (C) 2019 PRODA LTD
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by pbrisbin** [comment]
Nice, thanks!

**Comment by pbrisbin** [comment]
:wave: It's me again... This bug seems to still occur, but only if you invoke it with a certain kind of path.

```console
% cat issue-192.hs
#!/usr/bin/env stack
-- stack --resolver lts-16.0 script
main = pure ()
% stack exec brittany -- --version
brittany version 0.12.1.1
Copyright (C) 2016-2019 Lennart Spitzner
Copyright (C) 2019 PRODA LTD
There is NO WARRANTY, to the extent permitted by law.
```

```console
% stack exec brittany -- issue-192.hs
#!/usr/bin/env stack
-- stack --resolver lts-16.0 script
main = pure ()
% stack exec brittany -- ./issue-192.hs

-- stack --resolver lts-16.0 script#!/usr/bin/env stack

main = pure ()
```

So, `issue-192.hs` works, but `./issue-192.hs` doesn't work.

The bug also triggers on absolute paths or relative paths outside the current directory, but only if you `./` prefix them as well.

```console
% stack exec brittany -- x/issue-192.hs
#!/usr/bin/env stack
-- stack --resolver lts-16.0 script
main = pure ()
% stack exec brittany -- ./x/issue-192.hs

-- stack --resolver lts-16.0 script#!/usr/bin/env stack

main = pure ()
```

```console
% stack exec brittany -- ../../brittany-repro/issue-192.hs

-- stack --resolver lts-16.0 script#!/usr/bin/env stack

main = pure ()

```

:shrug: 

My editor plugin (ALE in vim) uses an absolute path to a tempfile, which is why the bug bites me so frequently.

**Comment by tfausak** [comment]
Oh dear. That's super weird.

**Comment by pbrisbin** [comment]
FYI, this seems to be the root cause: https://github.com/alanz/ghc-exactprint/issues/92 I got bit in HLint two (via refactor, via ghc-exact-print, which I believe Brittany uses as well).

**Comment by tfausak** [comment]
This has been fixed.
